#!/usr/bin/env python3
"""
Deployment Generator for Pyroclast

Generates production-ready deployment code for Executorch models.
Supports multiple templates: FastAPI, Docker, AWS Lambda, etc.
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, Any, Optional
import shutil

from pyroclast.utils import Colors, print_success, print_error, print_step


class DeploymentGenerator:
    """Generates deployment code for Executorch models"""

    TEMPLATES = ["fastapi", "docker", "lambda", "streamlit"]

    def __init__(
        self,
        model_path: str,
        output_dir: str = "./deployment",
        template: str = "fastapi",
        port: int = 8000,
        verbose: bool = False,
    ):
        self.model_path = Path(model_path)
        self.output_dir = Path(output_dir)
        self.template = template
        self.port = port
        self.verbose = verbose

        if not self.model_path.exists():
            raise FileNotFoundError(f"Model not found: {model_path}")

        if template not in self.TEMPLATES:
            raise ValueError(
                f"Unknown template: {template}. Choose from: {', '.join(self.TEMPLATES)}"
            )

    def generate(self) -> Path:
        """Generate deployment code based on template"""
        print_step(f"Generating {self.template} deployment for: {self.model_path.name}")

        # Create output directory
        self.output_dir.mkdir(parents=True, exist_ok=True)

        # Copy model file
        model_dest = self.output_dir / self.model_path.name
        if not model_dest.exists():
            shutil.copy2(self.model_path, model_dest)
            if self.verbose:
                print(f"  Copied model to: {model_dest}")

        # Generate template-specific files
        if self.template == "fastapi":
            self._generate_fastapi()
        elif self.template == "docker":
            self._generate_docker()
        elif self.template == "lambda":
            self._generate_lambda()
        elif self.template == "streamlit":
            self._generate_streamlit()

        print_success(f"Deployment code generated in: {self.output_dir}")
        return self.output_dir

    def _generate_fastapi(self):
        """Generate FastAPI deployment"""
        print_step("Generating FastAPI server...")

        # Generate app.py
        app_code = f'''"""
FastAPI server for Executorch model inference
Auto-generated by Pyroclast
"""

from fastapi import FastAPI, HTTPException
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from typing import List, Optional
import torch
import numpy as np
from pathlib import Path

# Executorch imports
try:
    from executorch.extension.pybindings.portable_lib import _load_for_executorch
except ImportError:
    _load_for_executorch = None

app = FastAPI(
    title="Executorch Model API",
    description="Production-ready API for Executorch model inference",
    version="1.0.0"
)

# Global model instance
MODEL_PATH = Path("{self.model_path.name}")
model = None


class InferenceRequest(BaseModel):
    """Request schema for inference"""
    inputs: List[List[float]]
    input_shape: Optional[List[int]] = None


class InferenceResponse(BaseModel):
    """Response schema for inference"""
    outputs: List[List[float]]
    shape: List[int]
    inference_time_ms: float


@app.on_event("startup")
async def load_model():
    """Load Executorch model on startup"""
    global model

    if _load_for_executorch is None:
        raise RuntimeError("Executorch not available")

    print(f"Loading model from {{MODEL_PATH}}...")
    model = _load_for_executorch(str(MODEL_PATH))
    print("Model loaded successfully!")


@app.get("/")
async def root():
    """Health check endpoint"""
    return {{
        "status": "healthy",
        "model": str(MODEL_PATH),
        "version": "1.0.0"
    }}


@app.get("/health")
async def health():
    """Detailed health check"""
    return {{
        "status": "healthy",
        "model_loaded": model is not None,
        "model_path": str(MODEL_PATH)
    }}


@app.post("/predict", response_model=InferenceResponse)
async def predict(request: InferenceRequest):
    """Run inference on input data"""
    if model is None:
        raise HTTPException(status_code=503, detail="Model not loaded")

    try:
        # Convert input to tensor
        input_data = torch.tensor(request.inputs, dtype=torch.float32)

        if request.input_shape:
            input_data = input_data.reshape(request.input_shape)

        # Time inference
        import time
        start = time.time()

        # Run inference
        outputs = model.forward((input_data,))

        inference_time = (time.time() - start) * 1000  # ms

        # Convert output to list
        if isinstance(outputs, (list, tuple)):
            output_tensor = outputs[0]
        else:
            output_tensor = outputs

        output_list = output_tensor.detach().cpu().numpy().tolist()

        return InferenceResponse(
            outputs=output_list,
            shape=list(output_tensor.shape),
            inference_time_ms=inference_time
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/batch_predict")
async def batch_predict(requests: List[InferenceRequest]):
    """Run inference on batch of inputs"""
    results = []

    for req in requests:
        try:
            result = await predict(req)
            results.append({{"success": True, "data": result}})
        except Exception as e:
            results.append({{"success": False, "error": str(e)}})

    return {{"results": results}}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port={self.port})
'''

        app_file = self.output_dir / "app.py"
        app_file.write_text(app_code)
        if self.verbose:
            print(f"  Generated: {app_file}")

        # Generate requirements.txt
        requirements = """fastapi==0.104.1
uvicorn[standard]==0.24.0
pydantic==2.5.0
torch>=2.0.0
executorch
numpy
"""
        req_file = self.output_dir / "requirements.txt"
        req_file.write_text(requirements)
        if self.verbose:
            print(f"  Generated: {req_file}")

        # Generate Dockerfile
        self._generate_docker_for_fastapi()

        # Generate README
        readme = f"""# Executorch Model API

FastAPI server for `{self.model_path.name}`

## Quick Start

### Install Dependencies

```bash
pip install -r requirements.txt
```

### Run Server

```bash
python app.py
# or
uvicorn app:app --host 0.0.0.0 --port {self.port}
```

### Test API

```bash
# Health check
curl http://localhost:{self.port}/health

# Inference
curl -X POST http://localhost:{self.port}/predict \\
  -H "Content-Type: application/json" \\
  -d '{{"inputs": [[1.0, 2.0, 3.0]], "input_shape": [1, 3]}}'
```

## Docker Deployment

```bash
# Build image
docker build -t executorch-api .

# Run container
docker run -p {self.port}:{self.port} executorch-api
```

## API Endpoints

- `GET /` - Root/health check
- `GET /health` - Detailed health status
- `POST /predict` - Single prediction
- `POST /batch_predict` - Batch predictions

## Auto-generated by Pyroclast

Modify as needed for your use case!
"""
        readme_file = self.output_dir / "README.md"
        readme_file.write_text(readme)
        if self.verbose:
            print(f"  Generated: {readme_file}")

    def _generate_docker_for_fastapi(self):
        """Generate Dockerfile for FastAPI deployment"""
        dockerfile = f"""FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application
COPY app.py .
COPY {self.model_path.name} .

# Expose port
EXPOSE {self.port}

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
  CMD curl -f http://localhost:{self.port}/health || exit 1

# Run application
CMD ["python", "app.py"]
"""
        dockerfile_path = self.output_dir / "Dockerfile"
        dockerfile_path.write_text(dockerfile)
        if self.verbose:
            print(f"  Generated: {dockerfile_path}")

    def _generate_docker(self):
        """Generate standalone Docker deployment"""
        print_step("Generating Docker deployment...")
        self._generate_fastapi()  # Docker uses FastAPI as base

    def _generate_lambda(self):
        """Generate AWS Lambda deployment"""
        print_step("Generating AWS Lambda deployment...")

        handler_code = f'''"""
AWS Lambda handler for Executorch model
Auto-generated by Pyroclast
"""

import json
import boto3
import torch
from pathlib import Path

# Load model (will be cached across invocations)
MODEL_PATH = Path("{self.model_path.name}")
model = None


def load_model():
    """Load model (called once per container)"""
    global model
    if model is None:
        from executorch.extension.pybindings.portable_lib import _load_for_executorch
        model = _load_for_executorch(str(MODEL_PATH))
    return model


def lambda_handler(event, context):
    """
    Lambda handler for model inference

    Event format:
    {{
        "inputs": [[1.0, 2.0, 3.0]],
        "input_shape": [1, 3]
    }}
    """
    try:
        # Parse input
        body = json.loads(event.get('body', '{{}}')) if isinstance(event.get('body'), str) else event

        inputs = body.get('inputs')
        input_shape = body.get('input_shape')

        if not inputs:
            return {{
                'statusCode': 400,
                'body': json.dumps({{'error': 'Missing inputs field'}})
            }}

        # Load model
        m = load_model()

        # Convert input
        input_tensor = torch.tensor(inputs, dtype=torch.float32)
        if input_shape:
            input_tensor = input_tensor.reshape(input_shape)

        # Run inference
        outputs = m.forward((input_tensor,))

        # Convert output
        if isinstance(outputs, (list, tuple)):
            output_tensor = outputs[0]
        else:
            output_tensor = outputs

        output_list = output_tensor.detach().cpu().numpy().tolist()

        return {{
            'statusCode': 200,
            'headers': {{'Content-Type': 'application/json'}},
            'body': json.dumps({{
                'outputs': output_list,
                'shape': list(output_tensor.shape)
            }})
        }}

    except Exception as e:
        return {{
            'statusCode': 500,
            'body': json.dumps({{'error': str(e)}})
        }}
'''

        handler_file = self.output_dir / "lambda_handler.py"
        handler_file.write_text(handler_code)

        # Lambda README
        readme = f"""# AWS Lambda Deployment

Lambda function for `{self.model_path.name}`

## Deployment Steps

### 1. Create Lambda Layer for Dependencies

```bash
# Create layer directory
mkdir -p python/lib/python3.10/site-packages

# Install dependencies
pip install torch executorch -t python/lib/python3.10/site-packages

# Create layer zip
zip -r executorch-layer.zip python/
```

### 2. Deploy Function

```bash
# Package function code
zip function.zip lambda_handler.py {self.model_path.name}

# Create Lambda function (using AWS CLI)
aws lambda create-function \\
  --function-name executorch-inference \\
  --runtime python3.10 \\
  --handler lambda_handler.lambda_handler \\
  --zip-file fileb://function.zip \\
  --role <YOUR_LAMBDA_ROLE_ARN>

# Add layer
aws lambda update-function-configuration \\
  --function-name executorch-inference \\
  --layers <LAYER_ARN>
```

### 3. Test

```bash
aws lambda invoke \\
  --function-name executorch-inference \\
  --payload '{{"inputs": [[1.0, 2.0, 3.0]], "input_shape": [1, 3]}}' \\
  output.json

cat output.json
```

## Auto-generated by Pyroclast
"""
        readme_file = self.output_dir / "README.md"
        readme_file.write_text(readme)

    def _generate_streamlit(self):
        """Generate Streamlit web app"""
        print_step("Generating Streamlit web app...")

        app_code = f'''"""
Streamlit web app for Executorch model
Auto-generated by Pyroclast
"""

import streamlit as st
import torch
import numpy as np
from pathlib import Path
import json

# Executorch imports
try:
    from executorch.extension.pybindings.portable_lib import _load_for_executorch
except ImportError:
    st.error("Executorch not available!")
    st.stop()

MODEL_PATH = Path("{self.model_path.name}")


@st.cache_resource
def load_model():
    """Load model (cached)"""
    return _load_for_executorch(str(MODEL_PATH))


st.title("🔥 Executorch Model Inference")
st.subheader(f"Model: {{MODEL_PATH.name}}")

# Sidebar
with st.sidebar:
    st.header("Configuration")
    input_method = st.radio("Input Method", ["Manual", "JSON"])

# Load model
try:
    model = load_model()
    st.success("✓ Model loaded successfully!")
except Exception as e:
    st.error(f"Failed to load model: {{e}}")
    st.stop()

# Input section
st.header("Input Data")

if input_method == "Manual":
    input_text = st.text_area(
        "Enter input values (comma-separated)",
        "1.0, 2.0, 3.0",
        help="Enter comma-separated values"
    )

    shape_text = st.text_input(
        "Input shape (optional)",
        "",
        help="e.g., 1,3 or leave empty"
    )

    if st.button("Run Inference", type="primary"):
        try:
            # Parse input
            values = [float(x.strip()) for x in input_text.split(',')]
            input_tensor = torch.tensor(values, dtype=torch.float32)

            # Reshape if needed
            if shape_text:
                shape = [int(x.strip()) for x in shape_text.split(',')]
                input_tensor = input_tensor.reshape(shape)

            # Run inference
            with st.spinner("Running inference..."):
                outputs = model.forward((input_tensor,))

            # Display results
            if isinstance(outputs, (list, tuple)):
                output_tensor = outputs[0]
            else:
                output_tensor = outputs

            st.success("✓ Inference completed!")

            col1, col2 = st.columns(2)
            with col1:
                st.metric("Input Shape", str(list(input_tensor.shape)))
            with col2:
                st.metric("Output Shape", str(list(output_tensor.shape)))

            st.subheader("Output")
            st.code(str(output_tensor.detach().cpu().numpy()), language="python")

        except Exception as e:
            st.error(f"Error: {{e}}")

else:  # JSON input
    json_input = st.text_area(
        "JSON Input",
        '{{"inputs": [[1.0, 2.0, 3.0]], "input_shape": [1, 3]}}',
        height=150
    )

    if st.button("Run Inference", type="primary"):
        try:
            data = json.loads(json_input)
            input_tensor = torch.tensor(data['inputs'], dtype=torch.float32)

            if 'input_shape' in data:
                input_tensor = input_tensor.reshape(data['input_shape'])

            with st.spinner("Running inference..."):
                outputs = model.forward((input_tensor,))

            if isinstance(outputs, (list, tuple)):
                output_tensor = outputs[0]
            else:
                output_tensor = outputs

            st.success("✓ Inference completed!")
            st.json({{
                "outputs": output_tensor.detach().cpu().numpy().tolist(),
                "shape": list(output_tensor.shape)
            }})

        except Exception as e:
            st.error(f"Error: {{e}}")
'''

        app_file = self.output_dir / "streamlit_app.py"
        app_file.write_text(app_code)

        # Requirements
        requirements = """streamlit>=1.28.0
torch>=2.0.0
executorch
numpy
"""
        req_file = self.output_dir / "requirements.txt"
        req_file.write_text(requirements)

        # README
        readme = f"""# Streamlit Web App

Interactive web interface for `{self.model_path.name}`

## Quick Start

```bash
# Install dependencies
pip install -r requirements.txt

# Run app
streamlit run streamlit_app.py
```

The app will open in your browser at `http://localhost:8501`

## Features

- Manual input entry
- JSON input format
- Real-time inference
- Result visualization

## Auto-generated by Pyroclast
"""
        readme_file = self.output_dir / "README.md"
        readme_file.write_text(readme)


def main():
    parser = argparse.ArgumentParser(
        description="Generate deployment code for Executorch models",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Generate FastAPI server
  python3 pyroclast_deployer.py model.pte -t fastapi

  # Generate Docker deployment
  python3 pyroclast_deployer.py model.pte -t docker -o ./deploy

  # Generate AWS Lambda
  python3 pyroclast_deployer.py model.pte -t lambda

  # Generate Streamlit app
  python3 pyroclast_deployer.py model.pte -t streamlit
        """,
    )

    parser.add_argument("model_path", help="Path to Executorch model (.pte file)")

    parser.add_argument("-o", "--output-dir", default="./deployment", help="Output directory")

    parser.add_argument(
        "-t",
        "--template",
        choices=DeploymentGenerator.TEMPLATES,
        default="fastapi",
        help="Deployment template",
    )

    parser.add_argument(
        "-p", "--port", type=int, default=8000, help="Server port (for FastAPI/Docker)"
    )

    parser.add_argument("-v", "--verbose", action="store_true", help="Verbose output")

    args = parser.parse_args()

    try:
        generator = DeploymentGenerator(
            model_path=args.model_path,
            output_dir=args.output_dir,
            template=args.template,
            port=args.port,
            verbose=args.verbose,
        )

        output_dir = generator.generate()

        print(f"\n{Colors.GREEN}✓ Deployment code generated!{Colors.RESET}")
        print(f"{Colors.CYAN}Location:{Colors.RESET} {output_dir}")
        print(f"\n{Colors.DIM}Check README.md for deployment instructions{Colors.RESET}")

        sys.exit(0)

    except Exception as e:
        print_error(f"Failed to generate deployment: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
